### ISSUE TITLE
RStudio requirements?

### ISSUE THREAD

**Issue by verdurin** [ComputeCanada/magic_castle#116]
I've been trying out the RStudio integration with Jupyter and I saw a `500` error.

The error logged in the job was:
```
[I 2020-09-14 16:44:13.059 SingleUserNotebookApp log:174] 302 GET /user/user01/rstudio? -> /user/user01/rstudio/ (user01@127.0.0.1) 1.06ms
[E 2020-09-14 16:44:13.114 SingleUserNotebookApp web:1792] Uncaught exception GET /user/user01/rstudio/ (127.0.0.1)
    HTTPServerRequest(protocol='https', host='jupyter.<MC cluster>', method='GET', uri='/user/user01/rstudio/', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/opt/jupyterhub/lib64/python3.6/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/opt/jupyterhub/lib64/python3.6/site-packages/jupyter_server_proxy/websocket.py", line 97, in get
        return await self.http_get(*args, **kwargs)
      File "/opt/jupyterhub/lib64/python3.6/site-packages/jupyter_server_proxy/handlers.py", line 534, in http_get
        return await self.proxy(self.port, path)
      File "/opt/jupyterhub/lib64/python3.6/site-packages/jupyter_server_proxy/handlers.py", line 528, in proxy
        await self.ensure_process()
      File "/opt/jupyterhub/lib64/python3.6/site-packages/jupyter_server_proxy/handlers.py", line 505, in ensure_process
        await proc.start()
      File "/opt/jupyterhub/lib64/python3.6/site-packages/simpervisor/process.py", line 91, in start
        *self._proc_args, **self._proc_kwargs
      File "/usr/lib64/python3.6/asyncio/subprocess.py", line 225, in create_subprocess_exec
        stderr=stderr, **kwds)
      File "/usr/lib64/python3.6/asyncio/base_events.py", line 1211, in subprocess_exec
        bufsize, **kwargs)
      File "/usr/lib64/python3.6/asyncio/unix_events.py", line 200, in _make_subprocess_transport
        **kwargs)
      File "/usr/lib64/python3.6/asyncio/base_subprocess.py", line 39, in __init__
        stderr=stderr, bufsize=bufsize, **kwargs)
      File "/usr/lib64/python3.6/asyncio/unix_events.py", line 706, in _start
        universal_newlines=False, bufsize=bufsize, **kwargs)
      File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
        restore_signals, start_new_session)
      File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'rserver': 'rserver'
```

Looking at issue #2 is it that I need to add `rstudio-server` to the default modules list?

If so, can that be done post-build?

**Comment by cmd-ntrf** [comment]
If you use the latest release of Magic Castle, it is configured to also use the latest release of jupyter-lmod which is responsible for adding the links to RStudio in the "New" notebook menu, or in the launcher if you use JupyterLab.

jupyter-lmod looks for the presence of "rstudio-server" module in the currently loaded module list. If it is loaded, the link appears, if it is not, the link is not added to the menu. This avoids the problem you had where the user tries to click on "RStudio" without first loading the required module.

If you wish to load rstudio-server by default, you can define `profile::cvmfs::client::lmod_default_modules`[1] with the default modules you like to be loaded for the users in the puppet hieradata[2]

[1] https://github.com/ComputeCanada/puppet-magic_castle#profilecvmfs
[2] https://github.com/ComputeCanada/magic_castle/tree/master/docs#412-hieradata-optional

**Comment by verdurin** [comment]
I see. Thanks for the explanation.
