### ISSUE TITLE
Permission Denied errors on files that are created/handled in jobs

### ISSUE THREAD

**Issue by casparvl** [ComputeCanada/magic_castle#198]
**Issue**
This is going to be a bit of a vague ticket, since I haven't been able to create a minimal reproducer. However, maybe someone recognizes it and knows what's going on.

I'm running some `ReFrame` (https://reframe-hpc.readthedocs.io/en/stable/) tests in a Magic Castle cluster. However, ReFrame finishes with a permission denied error. ReFrame is a bit 'special' in the sense that it will start as a process on the login node, and while running, it will submit jobs to run HPC tests. After those jobs complete, the ReFrame process on the login node (which is still running) will copy outputs from a staging to output directory, check for sanity patterns in the output file, etc. During this phase, ReFrame returns a permission denied error. However, if I manually check the file permissions, all seem to be ok (-rw-rw-r--).

The precise stacktrace is:

```
Traceback (most recent call last):
  File "/project/def-sponsor00/easybuild/software/ReFrame/3.9.2/lib/python3.9/site-packages/reframe/frontend/executors/__init__.py", line 267, in _safe_call
    return fn(*args, **kwargs)
  File "/project/def-sponsor00/easybuild/software/ReFrame/3.9.2/lib/python3.9/site-packages/reframe/core/hooks.py", line 80, in _fn
    func(obj, *args, **kwargs)
  File "/project/def-sponsor00/easybuild/software/ReFrame/3.9.2/lib/python3.9/site-packages/reframe/core/pipeline.py", line 2020, in cleanup
    self._copy_to_outputdir()
  File "/project/def-sponsor00/easybuild/software/ReFrame/3.9.2/lib/python3.9/site-packages/reframe/core/pipeline.py", line 1991, in _copy_to_outputdir
    shutil.copy2(f, self.outputdir)
  File "/cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/usr/lib/python3.9/shutil.py", line 436, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/usr/lib/python3.9/shutil.py", line 379, in copystat
    _copyxattr(src, dst, follow_symlinks=follow)
  File "/cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/usr/lib/python3.9/shutil.py", line 329, in _copyxattr
    os.setxattr(dst, name, value, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/home/casparl/reframe_hello/output/example_system/cpu/builtin/Hello/my_file'
```

The only thing that stands out here is the `follow_symlinks`, and I saw an earlier issue that mentioned a `Permission Denied` in the context of `symlinks` too, but no idea if these could be related: https://github.com/ComputeCanada/magic_castle/issues/138

At the suggestion of @ocaisa I ran the same workload from the Jupyter interface (i.e. I started a terminal Jupyter job). From there, it completes without issues.

**'Minimal' reproducer**

I haven't been able to reproduce it outside of `ReFrame`, I don't have a detailed enough overview of ReFrame's behaviour to mimic the behaviour closely enough... So, I guess you'll have to install ReFrame for this one, if you want to reproduce (see https://reframe-hpc.readthedocs.io/en/stable/started.html). Then, create a directory for this minimal example, and put the following two files there:

```
# hello.py
import reframe as rfm
import reframe.utility.sanity as sn
from reframe.core.backends import getlauncher

@rfm.simple_test
class Hello(rfm.RunOnlyRegressionTest):

    executable = 'echo'
    executable_opts += ['Hello > my_file']

    keep_files = ['my_file']

    valid_systems = ['*']
    valid_prog_environs = ['*']

    @run_after('setup')
    def set_launcher(self):
        self.job.launcher = getlauncher('local')()

    @sanity_function
    def validate(self):
        return sn.assert_found(rf'Hello', 'my_file')
```
```
#settings.py
site_configuration = {
    'systems': [
        {
            'name': 'example_system',
            'descr': 'This is just an example system',
            'modules_system': 'lmod',
            'hostnames': ['login', 'node'],
            'partitions': [
                {
                    'name': 'cpu',
                    'scheduler': 'slurm',
                    'launcher': 'mpirun',
                    'access':  ['-p cpubase_bycore_b1'],
                    'environs': ['builtin'],
                    'max_jobs': 4,
                    'descr': 'normal CPU partition'
                },
             ]
         },
     ],
    'environments': [
        {
            'name': 'builtin',
            'cc': 'cc',
            'cxx': '',
            'ftn': '',
        },
     ],
      'logging': [
         {
             'level': 'debug',
             'handlers': [
                 {
                     'type': 'stream',
                     'name': 'stdout',
                     'level': 'info',
                     'format': '%(message)s'
                 },
             ],
             'handlers_perflog': [
                 {
                     'type': 'filelog',
                     'prefix': '%(check_system)s/%(check_partition)s',
                     'level': 'info',
                     'append': True
                 }
             ]
         }
     ],
}
```
Note that you may have to change the partition name specified for `access` (simply specify any partition name where you want the job to run).
Then, assuming your current directory is the one with these two newly created files, you run:
```
reframe -c . -C settings.py -r 
```
Optionally, you can add `-vvvvv` to get the highest verbosity level.

I realize this is less then ideal as a 'minimal example', but it's the best I could do at this point...

**Comment by casparvl** [comment]
Oh, @ocaisa  had some good feedback on this:

> This is related to selinux, when you submit from JupyterHub you are already inside a job, so your context and the submitted job are the same (so no issues). When you use the login node, you are in a constrained context and can get a mismatch for submitted jobs

> The error in the logs is
```
Dec 14 12:21:11 login1 setroubleshoot[154299]: SELinux is preventing /cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/usr/bin/python3.9 from relabelto access on the file md.log.#012#012*****  Plugin restorecon_source (99.5 confidence) suggests   *****************#012#012If you want to fix the label. #012/cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/usr/bin/python3.9 default label should be default_t.#012Then you can run restorecon.#012Do#012# /sbin/restorecon -v /cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/usr/bin/python3.9#012#012*****  Plugin catchall (1.49 confidence) suggests   **************************#012#012If you believe that python3.9 should be allowed relabelto access on the md.log file by default.#012Then you should report this as a bug.#012You can generate a local policy module to allow this access.#012Do#012allow this access for now by executing:#012# ausearch -c 'reframe' --raw | audit2allow -M my-reframe#012# semodule -X 300 -i my-reframe.pp#012
```

I guess understanding that this is a limitation imposed by SELinux, it is probably intentional. Still pretty annoying for my use case, but not sure if there is anything that needs 'fixing' on your side: it might just be intended behaviour... :)
