### ISSUE TITLE
Invalid account or account/partition combination specified

### ISSUE THREAD

**Issue by brentwg** [ComputeCanada/magic_castle#219]
MC for Azure version: 11.9.3

Whenever any user attempt to submit a SLURM job, we get the following error message:
```
sbatch test_job.sh
[output]
sbatch: error: Batch job submission failed: Invalid account or account/partition combination specified
```
Never saw this one before. So I tried to manually create a new user and I got the following errors:
```
IPA_GUEST_PASSWD=${IPA_GUEST_PASSWD} /sbin/ipa_create_user.py test
[output]
2022-07-13,19:05:48.317 INFO {ipa_create_user} [user_add] adding user test (Try 1 / 5)
Traceback (most recent call last):
  File "/sbin/ipa_create_user.py", line 144, in <module>
    sshpubkeys=args.sshpubkey
  File "/sbin/ipa_create_user.py", line 112, in main
    for group in groups:
TypeError: 'NoneType' object is not iterable
```
I was adding the pub key later. Am I doing something wrong here?

**Comment by brentwg** [comment]
That you. the `sacctmgr` commands work great! Thank you so much for the quick turn around.
